### ISSUE TITLE
Running this program

### ISSUE THREAD

**Issue by AlyssaLytle** [hadley/data-movies#2]
Hello! What call do I make to this program to run it? (New to Ruby)

**Comment by Mohamed3on** [comment]
I second this. I'm also new to ruby and need to know how to install this.

**Comment by brycepg** [comment]
For Ubuntu 16.04, to get the dependencies:

```
sudo apt-get install ruby sqlite3 ruby-sqlite3 gzip wget
```

which gives me ruby 2.1.
After installing ruby, you need to install a ruby specific package using ruby's package manager, gem:

```
gem install arrayfields
```

After you have everything installed, see my response in #3. I use the code base from pull request #4.
